#!/usr/bin/env python3
"""Generate docs/compatibility.md from the registry + exported (non-synthetic) results in results-public/.

Status precedence per (artifact, backend): an observed run state (measured/OOM/failed/...)
from results-public/ wins over the registry's documented status. "verified" means that at least
one real run in results-public/ was measured with this exact artifact revision.
"""

from __future__ import annotations

import json
from collections import defaultdict

from llm_local_inference_sheet.config import PROJECT_ROOT, load_registry

BACKENDS = ["llama-cpp", "mlx-lm", "ollama"]
FORMAT_BACKENDS = {"gguf": {"llama-cpp", "ollama"}, "mlx": {"mlx-lm"}}


def observed() -> dict[tuple[str, str], dict[str, int]]:
    """Latest run per (experiment, cell); runtime states only (planner pre-states have no host info)."""
    latest: dict[tuple[str, str], tuple[str, dict]] = {}
    for man in (PROJECT_ROOT / "results-public").rglob("manifest.json"):
        if "report" in man.parts or "_scratch" in man.parts:
            continue
        m = json.loads(man.read_text())
        if not m.get("finished") or m.get("synthetic") or "host" not in m:
            continue
        key = (m["experiment"], m["cell_id"])
        run_id = man.parent.name
        if key not in latest or run_id > latest[key][0]:
            latest[key] = (run_id, m)
    obs: dict[tuple[str, str], dict[str, int]] = defaultdict(lambda: defaultdict(int))
    for _, m in latest.values():
        obs[(m["artifact"], m["backend"])][m["state"]] += 1
    return obs


def main() -> None:
    reg = load_registry()
    obs = observed()
    lines = [
        "# Compatibility matrix",
        "",
        "Generated by `scripts/gen_compat.py` from `configs/models.yaml` and the exported runs under `results-public/`.",
        "Do not edit the table by hand.",
        "",
        "Legend: **verified (n)** = n real runs measured here · *expected* = documented as supported, not yet run here ·",
        "*attempt* = outside the runtime's documented support matrix · **unsupported** = documented or observed not to work ·",
        "untested = no evidence · gated = needs licence acceptance + HF_TOKEN · `–` = format not loadable by that backend.",
        "Observed failures (OOM/failed/timeout) are shown with counts.",
        "",
        "| artifact | format / quant | " + " | ".join(BACKENDS) + " |",
        "|---|---|" + "|".join("---" for _ in BACKENDS) + "|",
    ]
    for m in reg.models:
        for a in m.artifacts:
            cells = []
            for b in BACKENDS:
                if b not in FORMAT_BACKENDS[a.format]:
                    cells.append("–")
                    continue
                o = obs.get((a.key, b))
                rc = a.runtimes.get(b)
                if o and o.get("measured"):
                    extra = "".join(f", {k} {v}" for k, v in o.items() if k != "measured")
                    cells.append(f"**verified ({o['measured']})**{extra}")
                elif o:
                    cells.append(", ".join(f"**{k}** ({v})" for k, v in o.items()))
                elif m.access == "gated":
                    cells.append("gated")
                elif rc:
                    s = {"expected": "*expected*", "attempt": "*attempt*", "unsupported": "**unsupported**"}.get(rc.status, rc.status)
                    cells.append(s)
                else:
                    cells.append("untested")
            lines.append(f"| `{a.key}` | {a.format} / {a.quantization.method} | " + " | ".join(cells) + " |")
    lines += ["", "## Hardware notes", "",
              "- Mac backends were run natively on an Apple M3 Pro (18 GB, 14 GPU cores, macOS 26.6.2)."]
    out = PROJECT_ROOT / "docs" / "compatibility.md"
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}")


if __name__ == "__main__":
    main()
